version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL:-http://localhost:8000}
    ports:
      - "3000:80"  # Changed from 8080 to 80
    environment:
      - VITE_API_URL=${VITE_API_URL:-http://localhost:8000}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]  # Changed from 8080 to 80
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s